name: Deploy PHP to Plesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Subir archivos PHP a Plesk
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /httpdocs/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
